spring:
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 16
  datasource:
    url: jdbc:mysql://localhost:3306/chouchou?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
  thymeleaf:
    cache: false


com:
  gaoc:
    base:
      minio:
        host: http://127.0.0.1
        post: 9000
        access-key: chouchou
        secret-key: Gemini0623
        expiry: 87600

